FROM python:3.10-slim-buster

# Update package manager and install AWS CLI
RUN apt update -y && apt install -y awscli

# Set the working directory
WORKDIR /app

# Copy the application code to the container
COPY . /app

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Command to run the application
CMD ["python3", "app.py"]